export interface Template {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  items: { name: string; quantity?: string }[];
  accentColor: string;
}

// Curated starter lists — for users with decision fatigue, tap one to populate the whole list
export const TEMPLATES: Template[] = [
  {
    id: 'weekly-basics',
    name: 'Weekly Basics',
    emoji: '🛒',
    tagline: 'Staples for any week',
    accentColor: '#4338CA',
    items: [
      { name: 'Milk', quantity: '1 gallon' },
      { name: 'Eggs', quantity: '1 dozen' },
      { name: 'Bread' },
      { name: 'Butter' },
      { name: 'Bananas' },
      { name: 'Chicken breast', quantity: '2 lbs' },
      { name: 'Rice' },
      { name: 'Pasta' },
      { name: 'Onions' },
      { name: 'Garlic' },
    ],
  },
  {
    id: 'pasta-night',
    name: 'Pasta Night',
    emoji: '🍝',
    tagline: 'One pot, eight ingredients',
    accentColor: '#A8442A',
    items: [
      { name: 'Pasta', quantity: '1 lb' },
      { name: 'Tomato sauce', quantity: '24 oz jar' },
      { name: 'Garlic' },
      { name: 'Parmesan' },
      { name: 'Ground beef', quantity: '1 lb' },
      { name: 'Onion' },
      { name: 'Olive oil' },
      { name: 'Basil' },
    ],
  },
  {
    id: 'healthy-week',
    name: 'Healthy Week',
    emoji: '🥗',
    tagline: 'Clean, lean, colorful',
    accentColor: '#5A8267',
    items: [
      { name: 'Chicken breast', quantity: '2 lbs' },
      { name: 'Salmon', quantity: '1 lb' },
      { name: 'Broccoli' },
      { name: 'Spinach' },
      { name: 'Sweet potato' },
      { name: 'Quinoa' },
      { name: 'Avocado', quantity: '3' },
      { name: 'Eggs', quantity: '1 dozen' },
      { name: 'Blueberries' },
      { name: 'Almonds' },
      { name: 'Greek yogurt' },
      { name: 'Lemon', quantity: '2' },
    ],
  },
  {
    id: 'breakfast',
    name: 'Big Breakfast',
    emoji: '🥞',
    tagline: 'Slow-morning ritual',
    accentColor: '#C97A18',
    items: [
      { name: 'Eggs', quantity: '1 dozen' },
      { name: 'Bacon' },
      { name: 'Bread' },
      { name: 'Butter' },
      { name: 'Milk' },
      { name: 'Coffee' },
      { name: 'Orange juice' },
      { name: 'Cereal' },
      { name: 'Maple syrup' },
      { name: 'Yogurt' },
    ],
  },
  {
    id: 'party',
    name: 'Party Night',
    emoji: '🎉',
    tagline: 'Friends are coming over',
    accentColor: '#F0996B',
    items: [
      { name: 'Chips' },
      { name: 'Pretzels' },
      { name: 'Salsa' },
      { name: 'Guacamole' },
      { name: 'Beer', quantity: '12 pack' },
      { name: 'Wine', quantity: '2 bottles' },
      { name: 'Soda' },
      { name: 'Ice' },
      { name: 'Cheese' },
      { name: 'Crackers' },
    ],
  },
  {
    id: 'comfort-food',
    name: 'Comfort Food',
    emoji: '🍲',
    tagline: 'Cozy weeknight wins',
    accentColor: '#9A8B70',
    items: [
      { name: 'Bread' },
      { name: 'Butter' },
      { name: 'Cheese' },
      { name: 'Soup' },
      { name: 'Pasta' },
      { name: 'Chicken' },
      { name: 'Rice' },
      { name: 'Potatoes' },
      { name: 'Carrots' },
      { name: 'Onion' },
    ],
  },
  {
    id: 'veggie-basics',
    name: 'Veggie Basics',
    emoji: '🥦',
    tagline: 'Plant-forward week',
    accentColor: '#7A8DC4',
    items: [
      { name: 'Tofu' },
      { name: 'Black beans' },
      { name: 'Lentils' },
      { name: 'Quinoa' },
      { name: 'Broccoli' },
      { name: 'Spinach' },
      { name: 'Tomatoes' },
      { name: 'Garlic' },
      { name: 'Olive oil' },
      { name: 'Mushrooms' },
      { name: 'Sweet potato' },
      { name: 'Bell pepper' },
    ],
  },
  {
    id: 'household',
    name: 'Household Run',
    emoji: '🧴',
    tagline: 'Restock the boring stuff',
    accentColor: '#9684C0',
    items: [
      { name: 'Toilet paper' },
      { name: 'Paper towels' },
      { name: 'Laundry detergent' },
      { name: 'Dish soap' },
      { name: 'Trash bags' },
      { name: 'Sponges' },
      { name: 'Toothpaste' },
      { name: 'Shampoo' },
    ],
  },
];
